FROM python:3.10-slim
LABEL authors="viewzen_labs"

COPY requirements.txt .

RUN pip install streamlit langchain langchain_core aiohttp aiofiles asyncio

COPY . .

CMD ["streamlit", "run", "app/streamlit.py"]