version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    environment:
      GOOGLE_API_KEY: AIzaSyA2-r052GsiexJokeCDeHpbZsBUt17dND0
    networks:
      - app_network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    depends_on:
      fastapi:
        condition: service_started
    ports:
      - "8501:8501"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
