version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    environment:
      GOOGLE_API_KEY: AIzaSyA2-r052GsiexJokeCDeHpbZsBUt17dND0
      SQLITE_DB_URL: "sqlite:////data/sqlite/chatpdf_sqlmanager.sql"
      VECTOR_DB_PATH: "/data/vector_store"
    networks:
      - app_network
    volumes:
      - sqlite_data:/data/sqlite
      - vectorstore_data:/data/vector_store

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    depends_on:
      fastapi:
        condition: service_started
    ports:
      - "8501:8501"
    networks:
      - app_network
    volumes:
      - sqlite_data:/data/sqlite
      - vectorstore_data:/data/vector_store

networks:
  app_network:
    driver: bridge

volumes:
  sqlite_data:
  vectorstore_data:
